name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - floating-base # Adjust this to the branch you want to trigger the workflow on
    paths:
      - 'docs/**' # Only trigger workflow if files in the docs folder are modified
      - '.github/workflows/gh-pages.yml' # Trigger workflow if the workflow file is modified

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install pydata_sphinx_theme

      - name: Build the Sphinx documentation
        run: |
          cd docs
          make clean
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
