name: Test and Verify Algorithm Results

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: '3.x'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy pybind11
        pip install requirements.txt

    - name: Build Extension
      run: |
        pip install .

    - name: Run tests
      run: | 
        pytest tests/python/ -v 
